In [1]:
import findspark
import pyspark
from pyspark.sql import SparkSession
from pyspark import SparkContext


spark = SparkSession \
    .builder \
    .appName("Pysparkexample") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()



df_load_6 = spark.read.csv('hdfs://192.168.122.206:8020/data/vol/departbis/*.csv',header='true')
#df_load_2 = spark.read.csv('hdfs://192.168.122.206:8020/data/vol/arriveebis/2020-03*.csv',header='true')

AnalysisException: 'Path does not exist: hdfs://192.168.122.206:8020/data/vol/departbis/*.csv;'

In [52]:
df_3=df_load_2.toPandas()
df_6=df_load_6.toPandas()

In [22]:
df_6.columns

Index(['acd', 'acr', 'act', 'alic', 'alna', 'alt', 'apdstci', 'apdstco',
       'apdstia', 'apdstic', 'apdstla', 'apdstlo', 'apdstst', 'apdsttz',
       'apdsttznl', 'apdsttzns', 'aporgci', 'aporgco', 'aporgia', 'aporgic',
       'aporgla', 'aporglo', 'aporgst', 'aporgtz', 'aporgtznl', 'aporgtzns',
       'aptkoic', 'arrau', 'arrc', 'arrdate', 'arrdelay', 'arre', 'arreu',
       'arrival', 'arrivalRelative', 'arrival_meta', 'arrs', 'arrsts', 'arrsu',
       'arrtaxi', 'cancel', 'cs', 'csalic', 'csalna', 'day', 'delay',
       'departure', 'departureRelative', 'departure_meta', 'depau', 'depc',
       'depdate', 'depdelay', 'depe', 'depeu', 'deps', 'depsts', 'depsu',
       'deptaxi', 'distance', 'duration', 'durationType', 'fid', 'firstla',
       'firstlaloci', 'firstlaloco', 'firstlalost', 'firstlalot', 'firstlo',
       'fnia', 'fnic', 'isFuture', 'lastla', 'lastlaloci', 'lastlaloco',
       'lastlalost', 'lastlalot', 'lastlo', 'lngsrc', 'lngtc', 'mrgarru',
       'mrgdepu', 'ms', 'pcnt', 'ph1', 'ph2', 'phu1', 'phu2', 'progress',
       'replay', 'so', 'status', 'statusLabel', 'svd', 'th1', 'th2', 'tkosrc',
       'tkotc'],
      dtype='object')

In [48]:
df_6[df_6.stattus=='landed']

AttributeError: 'DataFrame' object has no attribute 'stattus'

In [60]:
df_6[['depdelay','depe','depsts','depsu','depeu','delay','arrau','arreu','arrau','arrsu','fnic','fnia','aporgco','apdstco','aporgci','apdstci','arrdate','day','status','arrdelay']]

,depdelay,depe,depsts,depsu,depeu,delay,arrau,arreu,arrau,arrsu,fnic,fnia,aporgco,apdstco,aporgci,apdstci,arrdate,day,status,arrdelay
0,None,None,1582799335,None,None,None,None,None,None,None,DLH1401,LH1401,Germany,France,Munich,Lyon,"Thursday, February 27 2020",27 Feb,landed,None
1,None,None,1582799828,1582799100.0,None,None,None,None,None,None,EJU4827,U24827,Italy,France,Nápoli,Lyon,"Thursday, February 27 2020",27 Feb,landed,None
2,None,None,1582800900,1582800900.0,None,None,None,1582805760.0,None,1582806300.0,KLM1415,KL1415,Netherlands,France,Amsterdam,Lyon,"Thursday, February 27 2020",27 Feb,landed,None
3,None,None,1582802400,1582802400.0,None,None,1582805760.0,1582806600.0,1582805760.0,1582806600.0,AFR7652,AF7652,France,France,Paris,Lyon,"Thursday, February 27 2020",27 Feb,landed,None
4,None,None,1582803600,1582803600.0,None,360.0,1582808100.0,1582808460.0,1582808100.0,1582808100.0,DLH1076,LH1076,Germany,France,Frankfurt,Lyon,"Thursday, February 27 2020",27 Feb,landed,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,None,None,1584305400,1584305400.0,None,120.0,None,1584309720.0,None,1584309600.0,AFR7648,AF7648,France,France,Paris,Lyon,"Sunday, March 15 2020",15 Mar,landed,None
1869,None,None,1584305400,1584305400.0,None,None,None,1584309540.0,None,1584309900.0,DLH1082,LH1082,Germany,France,Frankfurt,Lyon,"Sunday, March 15 2020",15 Mar,landed,None
1870,None,None,1584304500,1584304500.0,None,None,None,1584310800.0,None,1584310800.0,IBE8722,IB8722,Spain,France,Madrid,Lyon,"Sunday, March 15 2020",15 Mar,landed,None
1871,None,None,1584303000,1584303000.0,None,51898.0,None,None,None,1584310800.0,TVF4859,TO4859,Tunisia,France,Monastir,Lyon,"Sunday, March 15 2020",15 Mar,cancelled,None
1872,None,None,1584302400,1584302400.0,None,None,None,1584310080.0,None,1584311100.0,TVF4839,TO4839,Portugal,France,Lisbon,Lyon,"Sunday, March 15 2020",15 Mar,landed,None

In [ ]:
dfdd[['']]